# Generated by Django 5.2.9 on 2026-05-08 01:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Mail Type',
                'verbose_name_plural': 'Mail Types',
            },
        ),
        migrations.CreateModel(
            name='InlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(help_text='CID referenced in the HTML template', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('mail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_images', to='templates.mailtype')),
            ],
            options={
                'ordering': ['mail_type', 'display_order', 'content_id'],
                'indexes': [models.Index(fields=['mail_type', 'content_id', 'is_active'], name='templates_i_mail_ty_dfbbf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('template_name', models.CharField(help_text='Unique identifier (e.g., welcome-email).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='HTML Content for the email.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_context', models.JSONField(blank=True, default=dict, help_text='Default values for variables (JSON format).')),
                ('available_variables', models.CharField(blank=True, default='', max_length=255)),
                ('mail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='templates.mailtype')),
            ],
            options={
                'ordering': ['mail_type__name', '-version'],
                'indexes': [models.Index(fields=['mail_type', 'is_active'], name='templates_e_mail_ty_343943_idx')],
            },
        ),
    ]
