# Generated by Django 5.2.9 on 2026-05-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('mailings', '0002_initial'),
        ('templates', '0001_initial'),
        ('test_mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testmailing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_mailings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmailing',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_mailings', to='templates.emailtemplate'),
        ),
        migrations.AddField(
            model_name='testmailing',
            name='mail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_mailings', to='templates.mailtype'),
        ),
        migrations.AddField(
            model_name='testmailing',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='test_mailings', to='client.client'),
        ),
        migrations.AddField(
            model_name='testmailing',
            name='sender_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_mailings', to='mailings.senderemail'),
        ),
        migrations.AddField(
            model_name='testmailingattachment',
            name='test_mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='test_mailing.testmailing'),
        ),
        migrations.AddField(
            model_name='testmailingprocessedchunk',
            name='test_mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_chunks', to='test_mailing.testmailing'),
        ),
        migrations.AddIndex(
            model_name='testmailing',
            index=models.Index(fields=['status', 'scheduled_time'], name='test_mailin_status_4877a5_idx'),
        ),
        migrations.AddIndex(
            model_name='testmailing',
            index=models.Index(fields=['created_by', 'status'], name='test_mailin_created_f8971f_idx'),
        ),
        migrations.AddIndex(
            model_name='testmailingattachment',
            index=models.Index(fields=['test_mailing'], name='test_mailin_test_ma_32d316_idx'),
        ),
        migrations.AddIndex(
            model_name='testmailingprocessedchunk',
            index=models.Index(fields=['test_mailing', 'chunk_index'], name='test_mailin_test_ma_b4dd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='testmailingprocessedchunk',
            index=models.Index(fields=['test_mailing', 'status'], name='test_mailin_test_ma_cbff24_idx'),
        ),
        migrations.AddIndex(
            model_name='testmailingprocessedchunk',
            index=models.Index(fields=['original_task_id'], name='test_mailin_origina_5913a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testmailingprocessedchunk',
            unique_together={('test_mailing', 'chunk_index')},
        ),
    ]
