# Generated by Django 5.2.9 on 2026-05-08 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('mailings', '0002_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused')], db_index=True, default='DRAFT', max_length=20)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, default='DAILY', max_length=20)),
                ('send_at_time', models.TimeField(help_text='e.g., 09:00 AM')),
                ('target_weekday', models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21st'), (22, '22nd'), (23, '23rd'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th'), (29, '29th'), (30, '30th'), (31, '31st')], null=True)),
                ('month_of_year', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('context_variables', models.JSONField(blank=True, default=dict)),
                ('last_executed_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Last time this campaign was executed', null=True)),
                ('execution_count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of times this campaign has been executed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_periodic_task', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='templates.emailtemplate')),
                ('recipients', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='campaigns', to='client.client')),
                ('sender_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailings.senderemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='campaign_attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='DISPATCHED', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('completed_chunks', models.PositiveIntegerField(default=0)),
                ('successful_sends', models.PositiveIntegerField(default=0)),
                ('failed_sends', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'schedule_type'], name='campaigns_c_status_badff4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['email_template'], name='campaigns_c_email_t_370645_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sender_email'], name='campaigns_c_sender__c7f596_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['last_executed_at'], name='campaigns_c_last_ex_ab55bc_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['campaign'], name='campaigns_a_campaig_12c6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrun',
            index=models.Index(fields=['campaign', '-started_at'], name='campaigns_c_campaig_25aecb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrun',
            index=models.Index(fields=['status', '-started_at'], name='campaigns_c_status_4e765d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrun',
            index=models.Index(fields=['task_id'], name='campaigns_c_task_id_388469_idx'),
        ),
    ]
