# Generated by Django 5.2.9 on 2026-05-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='execution_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.UniqueConstraint(fields=('campaign', 'task_id'), name='unique_campaign_run_per_task', violation_error_message='A CampaignRun already exists for this campaign and task.'),
        ),
    ]
