# Generated by Django 5.2.9 on 2026-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('context_variables', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('completed_chunks', models.PositiveIntegerField(default=0)),
                ('successful_sends', models.PositiveIntegerField(default=0)),
                ('failed_sends', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mailings/attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', editable=False, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mailing Attachment',
                'verbose_name_plural': 'Mailing Attachments',
            },
        ),
        migrations.CreateModel(
            name='MailingProcessedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=20)),
                ('original_task_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('campaign_name', models.CharField(blank=True, db_index=True, help_text='Used by test_mailings for traceability.', max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], db_index=True, default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Mail Log',
                'verbose_name_plural': 'Mail Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Sender Email',
                'verbose_name_plural': 'Sender Emails',
            },
        ),
    ]
