# Generated by Django 5.2.9 on 2026-05-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('mailings', '0001_initial'),
        ('templates', '0001_initial'),
        ('test_mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mailings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='templates.emailtemplate'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='templates.mailtype'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='mailings', to='client.client'),
        ),
        migrations.AddField(
            model_name='mailingattachment',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailings.mailing'),
        ),
        migrations.AddField(
            model_name='mailingprocessedchunk',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_chunks', to='mailings.mailing'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='client.client'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maillog',
            name='mail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.mailtype'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='mailings.mailing'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='scheduled_mailing',
            field=models.ForeignKey(blank=True, help_text='Links log to TestMailing for admin drill-through.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='test_mailing.testmailing'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='templates.emailtemplate'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='sender_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailings.senderemail'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='sender_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='mailings.senderemail'),
        ),
        migrations.AddIndex(
            model_name='mailingattachment',
            index=models.Index(fields=['mailing'], name='mailings_ma_mailing_8d9be3_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingprocessedchunk',
            index=models.Index(fields=['mailing', 'chunk_index'], name='mailings_ma_mailing_b85ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingprocessedchunk',
            index=models.Index(fields=['mailing', 'status'], name='mailings_ma_mailing_307fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingprocessedchunk',
            index=models.Index(fields=['original_task_id'], name='mailings_ma_origina_d0b545_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailingprocessedchunk',
            unique_together={('mailing', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['client', '-sent_at'], name='mailings_ma_client__f87906_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['status', '-sent_at'], name='mailings_ma_status_34b82c_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['mailing', '-sent_at'], name='mailings_ma_mailing_ea9cde_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['campaign_name'], name='mailings_ma_campaig_80fa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['scheduled_mailing', '-sent_at'], name='mailings_ma_schedul_8d0156_idx'),
        ),
        migrations.AddConstraint(
            model_name='maillog',
            constraint=models.CheckConstraint(condition=models.Q(('mailing__isnull', True), ('scheduled_mailing__isnull', True), _connector='OR'), name='maillog_single_campaign_fk', violation_error_message='A log entry cannot belong to both a Mailing and a TestMailing.'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['status', '-created_at'], name='mailings_ma_status_9eb927_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['created_by', 'status'], name='mailings_ma_created_c68827_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['id', 'status'], name='mailings_ma_id_d02b19_idx'),
        ),
    ]
